ToDoList/Models/ErrorViewModel.cs
namespace ToDoList.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ToDoList/Models/ToDoListContext.cs
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace ToDoList.Models
{
    public partial class ToDoListContext : DbContext
    {
        public ToDoListContext()
        {
        }

        public ToDoListContext(DbContextOptions<ToDoListContext> options)
            : base(options)
        {
        }

        public virtual DbSet<ToDoListTable> ToDoListTables { get; set; } = null!;

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
//#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
//                optionsBuilder.UseSqlServer("Server=.\\sqlexpress;Database=ToDoList;Trusted_Connection=True;MultipleActiveResultSets=true");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<ToDoListTable>(entity =>
            {
                entity.ToTable("ToDoListTable");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}

ToDoList/Models/ToDoListTable.cs
using System;
using System.Collections.Generic;

namespace ToDoList.Models
{
    public partial class ToDoListTable
    {
        public int Id { get; set; }
        public string Task { get; set; } = null!;
    }
}

ToDoList/Controllers/TodoController.cs
using Microsoft.AspNetCore.Mvc;
using ToDoList.Models;

namespace ToDoList.Controllers
{
    public class TodoController : Controller
    {
        private readonly  ToDoListContext _context;
        public TodoController(ToDoListContext context)
        { 
            _context = context;    
        }
        public IActionResult Index()
        {
            IQueryable<ToDoListTable> ListAll = from i in _context.ToDoListTables orderby i.Id
                                                  select i;

            return View(ListAll);
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ToDoListTable _toDoListTable)
        {
            if ( (_toDoListTable != null) && (ModelState.IsValid))
            {
                _context.ToDoListTables.Add(_toDoListTable);
                _context.SaveChanges();

                TempData["Success"] = "新增成功";
                return RedirectToAction("Index");
            }
            else
            {
                TempData["Error"] = "新增失敗";
            }
            return View();
        }
        public IActionResult Edit(int id)
        {
            if (id == null)
            {
                return new StatusCodeResult((int)System.Net.HttpStatusCode.BadRequest);
            }

            ToDoListTable item = _context.ToDoListTables.Find(id);
            if (item == null)
            {
                return NotFound();
            }
            else
            {
                return View(item);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(ToDoListTable toDoListTable)
        {
            if (ModelState.IsValid)
            {
                _context.ToDoListTables.Update(toDoListTable);
                _context.SaveChanges();

                TempData["Success"] = "修改成功";
                return RedirectToAction("Index");
            }
            else
            {
                TempData["Error"] = "修改失敗";
            }
            return View();
        }
        public IActionResult Delete(int id)
        {
            ToDoListTable item = _context.ToDoListTables.Find(id);

            if (item == null)
            {
                TempData["Error"] = "此筆資料不存在";
            }
            else
            {
                _context.ToDoListTables.Remove(item);
                _context.SaveChanges();

                TempData["Success"] = "刪除成功";
            }
            return RedirectToAction("Index");
        }


    }
}

ToDoList/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ToDoList</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ToDoList.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Todo" asp-action="Index">ToDoList</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
@*                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>*@
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @if (TempData["Success"] != null)
            {
                <div class="alert alert-success">
                    @TempData["Success"]
                </div>
            }
            @if (TempData["Error"] != null)
            {
                <div class="alert alert-success">
                    @TempData["Error"]
                </div>
            }
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ToDoList - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ToDoList/Views/Todo/Create.cshtml
@model ToDoList.Models.ToDoListTable

@{
    ViewData["Title"] = "Create";
}

<h1>新增代辦事項</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Task" class="control-label"></label>
                <input asp-for="Task" class="form-control" />
                <span asp-validation-for="Task" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ToDoList/Views/Todo/Edit.cshtml
@model ToDoList.Models.ToDoListTable

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>ToDoListTable</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Task" class="control-label"></label>
                <input asp-for="Task" class="form-control" />
                <span asp-validation-for="Task" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ToDoList/Views/Todo/Index.cshtml
@model IEnumerable<ToDoList.Models.ToDoListTable>

@{
    ViewData["Title"] = "Index";
}

<p>
    <a asp-action="Create">Add new ToDo Item</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Task)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Task)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new {  id=item.Id  }) |
                @Html.ActionLink("Delete", "Delete", new {  id=item.Id  })
            </td>
        </tr>
}
    </tbody>
</table>